# a=open("E:\simple.txt")
# # print(a.tell())
# print(a.read())
# # print(a.tell())
# # print(a.seek(0))
# # print(a.read())
# # print(a.tell())
# # print(a.name)
# print(a.closed)
# # print(len(a.readline()))
# # print(a.readline(),end="")
# # print(a.readline(),end="")
# # print(a.readline())
# a.close()
# print(a.closed)
# with open(r"C:\Users\Hamza\PycharmProjects\HamzaAnsari\links.txt") as oo:
#     aa=oo.read()
#     print(aa)